version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverless-discord-bot"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-13r6o9d6oeqrd"
s3_prefix = "serverless-discord-bot"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
